### ISSUE TITLE
Kesalahan Rumus

### ISSUE THREAD

**Issue by rizkyfauziilmi** [RizkyFauziIlmi/project-simulasi-gerak-jatuh-bebas#3]
seharusnya rumus untuk mencari kecepatan setiap saat adalah Vy(t) = -gt dan untuk mencari posisi setiap saat adalah Y(t) = Y0 - 1/2gt^2 + v0.t

**Comment by Candimadam** [comment]
seharusnya rumus untuk mencari kecepatan setiap saat adalah Vy(t) = -gt dan untuk mencari posisi setiap saat adalah Y(t) = Y0 + 1/2gt^2 + v0.t
